language: node_js

install:
  - npm install

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: test
      script:
        # Run tests
        - npm run test
    - stage: build
      script:
        # Build all
        - npm run build
