language: node_js

node_js: 12

install:
  - |
    npm ci

stages:
  - name: test

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run build
        # - npm test
